name: Build iTorrent

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  
jobs:
  build:
    name: Build iTorrent
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Cocoapods
        run: sudo gem install cocoapods

      - name: Build pods
        run: pod install

      - name: Build
        run: xcodebuild -workspace iTorrent.xcworkspace -scheme iTorrent -destination 'platform=iOS Simulator,name=iPhone 8,OS=16.2' build      
